/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILayer;

import DataLayer.AddManager;
import DataLayer.EditManager;
import static GUILayer.GUI.convertdate;
import POJO.Student;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author --Client-ServEr--
 */
public class EditStudent extends java.awt.Dialog {
    private String StudentID;
    private String First_Name;
    private String Last_Name;
    private boolean Gender;
    private Date BirthDay;
    private String Mobile;
    private String Email;
    private String Address;
    private String ClassID;
    private String Description;
    private int Status;
     private Login Login=new Login(null,true);

 //Dinh nghia cac phuong thuc Get/Set
    public void SetStudentID(String StudentID)
    {
        this.StudentID=StudentID;
    }
    public String GetStudentID()
    {
        return StudentID;
    }
    public void SetFirstName(String FirstName)
    {
        this.First_Name=FirstName;
    }
    public String GetFirstName()
    {
        return First_Name;
    }
    public void SetLastName(String LastName)
    {
        this.Last_Name=LastName;
    }
    public String GetLastName()
    {
        return Last_Name;
    }
    public void SetGender(boolean Gender)
    {
        this.Gender=Gender;
    }
    public Boolean GetaGender()
    {
        return Gender;
    }
    public void SetBirthDay(Date BirthDay)
    {
        this.BirthDay=BirthDay;
    }
    public Date GetBirthDay()
    {
        return BirthDay;
    }
    public void SetMobile(String Mobile)
    {
        this.Mobile=Mobile;
    }
    public String GetMobile()
    {
        return Mobile;
    }
    public void SetEmail(String Email)
    {
        this.Email=Email;
    }
    public String GetEmail()
    {
        return Email;
    }
    public void SetAddress(String Address)
    {
        this.Address=Address;
    }
    public String GetAddress()
    {
        return Address;
    }
    public void SetClassID(String ClassID)
    {
        this.ClassID=ClassID;
    }
    public String GetClassID()
    {
        return ClassID;
    }
    public void SetDescription(String Description)
    {
        this.Description=Description;
    }
    public String GetDescription()
    {
        return Description;
    }
    public void SetStatus(int Status)
    {
        this.Status=Status;
    }
    public int GetStatus()
    {
        return Status;
    }
    public void SetLogin(Login login)
    {
        this.Login=login;
    }

    /**
     * Creates new form EditStudent
     */
    public EditStudent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFFirstNameEditStudent = new javax.swing.JTextField();
        JTFLastNameEditStudent = new javax.swing.JTextField();
        JCBGenderEditStudent = new javax.swing.JComboBox();
        JDCBirthDayEditStudent = new com.toedter.calendar.JDateChooser();
        JTFMobileEditStudent = new javax.swing.JTextField();
        JTFEmailEditStudent = new javax.swing.JTextField();
        JTFAddressEditStudent = new javax.swing.JTextField();
        JTFClassIDEditStudent = new javax.swing.JTextField();
        JTFDescriptionEditStudent = new javax.swing.JTextField();
        JBTEditEditStudent = new javax.swing.JButton();
        JCBSatusEditStudent = new javax.swing.JComboBox();
        JTFStudentIDEditStudent = new javax.swing.JTextField();
        JLBStudentID = new javax.swing.JLabel();
        JLBFirstName = new javax.swing.JLabel();
        JLBLastName = new javax.swing.JLabel();
        JLBGender = new javax.swing.JLabel();
        JLBBirthDay = new javax.swing.JLabel();
        JLBMobile = new javax.swing.JLabel();
        JLBEmail = new javax.swing.JLabel();
        JLBAddress = new javax.swing.JLabel();
        JLBDescription = new javax.swing.JLabel();
        JLBStatus = new javax.swing.JLabel();
        JLBClassID = new javax.swing.JLabel();
        JBTCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 34, 43));
        setTitle("Edit Student");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        JCBGenderEditStudent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        JBTEditEditStudent.setText("Edit");
        JBTEditEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTEditEditStudentActionPerformed(evt);
            }
        });

        JCBSatusEditStudent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0" }));

        JLBStudentID.setForeground(new java.awt.Color(255, 255, 255));
        JLBStudentID.setText("StudentID");

        JLBFirstName.setForeground(new java.awt.Color(255, 255, 255));
        JLBFirstName.setText("FirstName");

        JLBLastName.setForeground(new java.awt.Color(255, 255, 255));
        JLBLastName.setText("LastName");

        JLBGender.setForeground(new java.awt.Color(255, 255, 255));
        JLBGender.setText("Gender");

        JLBBirthDay.setForeground(new java.awt.Color(255, 255, 255));
        JLBBirthDay.setText("BitrhDay");

        JLBMobile.setForeground(new java.awt.Color(255, 255, 255));
        JLBMobile.setText("Mobile");

        JLBEmail.setForeground(new java.awt.Color(255, 255, 255));
        JLBEmail.setText("Email");

        JLBAddress.setForeground(new java.awt.Color(255, 255, 255));
        JLBAddress.setText("Address");

        JLBDescription.setForeground(new java.awt.Color(255, 255, 255));
        JLBDescription.setText("Description");

        JLBStatus.setForeground(new java.awt.Color(255, 255, 255));
        JLBStatus.setText("Status");

        JLBClassID.setForeground(new java.awt.Color(255, 255, 255));
        JLBClassID.setText("ClassID");

        JBTCancel.setText("Cancel");
        JBTCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLBStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTFAddressEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JLBClassID, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(JTFClassIDEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JCBSatusEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(JBTEditEditStudent)
                                .addGap(26, 26, 26)
                                .addComponent(JBTCancel))
                            .addComponent(JTFDescriptionEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JCBGenderEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFFirstNameEditStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(JTFStudentIDEditStudent))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JLBLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                    .addComponent(JLBBirthDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JDCBirthDayEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFLastNameEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(JTFMobileEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFEmailEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFStudentIDEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBStudentID))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JTFFirstNameEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLBFirstName)
                                .addComponent(JLBLastName))
                            .addComponent(JTFLastNameEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JCBGenderEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLBBirthDay))
                            .addComponent(JDCBirthDayEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JLBGender))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFMobileEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBMobile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFEmailEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFAddressEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFClassIDEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBAddress)
                    .addComponent(JLBClassID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFDescriptionEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBSatusEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBStatus)
                    .addComponent(JBTEditEditStudent)
                    .addComponent(JBTCancel))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        setBounds(470, 200, 459, 368);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void JBTEditEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTEditEditStudentActionPerformed
        // TODO add your handling code here:
         
        AddManager add=new AddManager();
          EditManager edit=new EditManager();
        Student stu=new Student();
       
        int check1,check2,Status;boolean Sex;
        check1=add.CheckStudentID(this.JTFStudentIDEditStudent.getText(), Login);
        check2=add.CheckClassID(this.JTFClassIDEditStudent.getText(), Login);
        if(check1==0)
        {
            JOptionPane.showMessageDialog(null,"StudentID is  Incorect!");
        }
        else
        {
            if(check2==0)
            {
                JOptionPane.showMessageDialog(null,"ClassID is  Incorect!");
            }
            else
            {
                stu.SetStudentID(this.JTFStudentIDEditStudent.getText());
                stu.SetFirstName(this.JTFFirstNameEditStudent.getText());
                stu.SetLastName(this.JTFLastNameEditStudent.getText());
                String vt=(String)this.JCBGenderEditStudent.getSelectedItem().toString();;
                Sex=vt.equals("Male");
                stu.SetGender(Sex);
                stu.SetBirthDay(convertdate(this.JDCBirthDayEditStudent.getDate()));
                stu.SetMobile(this.JTFMobileEditStudent.getText());
                stu.SetEmail(this.JTFEmailEditStudent.getText());
                stu.SetAddress(this.JTFAddressEditStudent.getText());
                stu.SetClassID(this.JTFClassIDEditStudent.getText());
                stu.SetDescription(this.JTFDescriptionEditStudent.getText());
                vt=(String)this.JCBSatusEditStudent.getSelectedItem().toString();
                Status=Integer.parseInt(vt);
                stu.SetStatus(Status);
                edit.EditStudentManager(stu, Login);
                this.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_JBTEditEditStudentActionPerformed

    private void JBTCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_JBTCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditStudent dialog = new EditStudent(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTCancel;
    private javax.swing.JButton JBTEditEditStudent;
    public javax.swing.JComboBox JCBGenderEditStudent;
    private javax.swing.JComboBox JCBSatusEditStudent;
    public com.toedter.calendar.JDateChooser JDCBirthDayEditStudent;
    private javax.swing.JLabel JLBAddress;
    private javax.swing.JLabel JLBBirthDay;
    private javax.swing.JLabel JLBClassID;
    private javax.swing.JLabel JLBDescription;
    private javax.swing.JLabel JLBEmail;
    private javax.swing.JLabel JLBFirstName;
    private javax.swing.JLabel JLBGender;
    private javax.swing.JLabel JLBLastName;
    private javax.swing.JLabel JLBMobile;
    private javax.swing.JLabel JLBStatus;
    private javax.swing.JLabel JLBStudentID;
    public javax.swing.JTextField JTFAddressEditStudent;
    public javax.swing.JTextField JTFClassIDEditStudent;
    public javax.swing.JTextField JTFDescriptionEditStudent;
    public javax.swing.JTextField JTFEmailEditStudent;
    public javax.swing.JTextField JTFFirstNameEditStudent;
    public javax.swing.JTextField JTFLastNameEditStudent;
    public javax.swing.JTextField JTFMobileEditStudent;
    public javax.swing.JTextField JTFStudentIDEditStudent;
    // End of variables declaration//GEN-END:variables

   
}
