/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILayer;

import javax.swing.JOptionPane;

/**
 *
 *  @author Bat Computer
 */
public class EditOrganization extends javax.swing.JDialog {
 private String OrganizationID;
    private String OrganizationName;
    private String Participation;
    private String Manager;
    private String Mobile;
    private String Email;
    private Login Login=new Login(null,true);
    
    //Dinh nghia cac phuong thuc Get/Set
    public void SetOrganizationID(String OrganizationID)
    {
        this.OrganizationID=OrganizationID;
    }
    public String GetOrganizationID()
    {
        return OrganizationID;
    }
     public void SetOrganizationName(String OrganizationName)
    {
        this.OrganizationName=OrganizationName;
    }
    public String GetOrganizationName()
    {
        return OrganizationName;
    }
     public void SetParticipation(String Participation)
    {
        this.Participation=Participation;
    }
    public String GetParticipation()
    {
        return Participation;
    }
     public void SetManager(String Manager)
    {
        this.Manager=Manager;
    }
    public String GetManager()
    {
        return Manager;
    }
     public void SetMobile(String Mobile)
    {
        this.Mobile=Mobile;
    }
    public String GetMobile()
    {
        return Mobile;
    }
     public void SetEmail(String Email)
    {
        this.Email=Email;
    }
    public String GetEmail()
    {
        return Email;
    }
     public void SetLogin(Login login)
    {
        this.Login=login;
    }
    /**
     * Creates new form EditOrganization
     */
    public EditOrganization(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFOrganizationIDEditOrganization = new javax.swing.JTextField();
        JTFOrganizationNameEditOrganization = new javax.swing.JTextField();
        JTFmanagerEditOrganization = new javax.swing.JTextField();
        JTFMobileEditOrganization = new javax.swing.JTextField();
        JTFEmailEditOrganziation = new javax.swing.JTextField();
        JBTEditOrganization = new javax.swing.JButton();
        JBTCancel = new javax.swing.JButton();
        JLBOrganizationID = new javax.swing.JLabel();
        JLBOrganizationName = new javax.swing.JLabel();
        JLBManager = new javax.swing.JLabel();
        JLBMobile = new javax.swing.JLabel();
        JLBEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Organization");
        setBackground(new java.awt.Color(31, 34, 43));

        JBTEditOrganization.setText("Edit");
        JBTEditOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTEditOrganizationActionPerformed(evt);
            }
        });

        JBTCancel.setText("Cancel");
        JBTCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTCancelActionPerformed(evt);
            }
        });

        JLBOrganizationID.setForeground(new java.awt.Color(255, 255, 255));
        JLBOrganizationID.setText("OrganizationID");

        JLBOrganizationName.setForeground(new java.awt.Color(255, 255, 255));
        JLBOrganizationName.setText("Organization Name");

        JLBManager.setForeground(new java.awt.Color(255, 255, 255));
        JLBManager.setText("Manager");

        JLBMobile.setForeground(new java.awt.Color(255, 255, 255));
        JLBMobile.setText("Mobile");

        JLBEmail.setForeground(new java.awt.Color(255, 255, 255));
        JLBEmail.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLBOrganizationID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBOrganizationName, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(JLBManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBTEditOrganization)
                        .addGap(18, 18, 18)
                        .addComponent(JBTCancel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JTFOrganizationIDEditOrganization)
                        .addComponent(JTFOrganizationNameEditOrganization)
                        .addComponent(JTFmanagerEditOrganization)
                        .addComponent(JTFMobileEditOrganization)
                        .addComponent(JTFEmailEditOrganziation, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFOrganizationIDEditOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBOrganizationID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFOrganizationNameEditOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBOrganizationName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFmanagerEditOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBManager))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFMobileEditOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBMobile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFEmailEditOrganziation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTEditOrganization)
                    .addComponent(JBTCancel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setBounds(470, 200, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void JBTEditOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTEditOrganizationActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JBTEditOrganizationActionPerformed

    private void JBTCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_JBTCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOrganization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOrganization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOrganization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOrganization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditOrganization dialog = new EditOrganization(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTCancel;
    private javax.swing.JButton JBTEditOrganization;
    private javax.swing.JLabel JLBEmail;
    private javax.swing.JLabel JLBManager;
    private javax.swing.JLabel JLBMobile;
    private javax.swing.JLabel JLBOrganizationID;
    private javax.swing.JLabel JLBOrganizationName;
    public javax.swing.JTextField JTFEmailEditOrganziation;
    public javax.swing.JTextField JTFMobileEditOrganization;
    public javax.swing.JTextField JTFOrganizationIDEditOrganization;
    public javax.swing.JTextField JTFOrganizationNameEditOrganization;
    public javax.swing.JTextField JTFmanagerEditOrganization;
    // End of variables declaration//GEN-END:variables
}
