/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILayer;

import javax.swing.JOptionPane;

/**
 *
 *  @author Bat Computer
 */
public class EditClass extends javax.swing.JDialog {
  
    //Dinh nghia cac thuoc tinh
    private String ClassID;
    private String ClassName;
    private int Year;
    private String MoniterID;
    private String DepartmentID;
    private Login Login=new Login(null,true);
     
    //Dinh nghia cac phuong thuc Get/Set
    public void SetClassID(String ClassID)
    {
        this.ClassID=ClassID;
    }
    public String GetClassID()
    {
        return ClassID;
    }
    public void SetClassName(String ClassName)
    {
        this.ClassName=ClassName;
    }
    public String GetClassName()
    {
        return ClassName;
    }
    public void SetYear(int Year)
    {
        this.Year=Year;
    }
    public int GetYear()
    {
        return Year;
    }
    public void SetMoniterID(String MoniterID)
    {
        this.MoniterID=MoniterID;
    }
    public String GetMoniterID()
    {
        return MoniterID;
    }
    public void SetDepartmentID(String DepartmentID)
    {
        this.DepartmentID=DepartmentID;
    }
    public String GetDepartmentID()
    {
        return DepartmentID;
    }
     public void SetLogin(Login login)
    {
        this.Login=login;
    }
    /**
     * Creates new form EditClass
     */
    public EditClass(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFClassIDEditClass = new javax.swing.JTextField();
        JTFClassnameEditClass = new javax.swing.JTextField();
        JCBYearEditClass = new javax.swing.JComboBox();
        JTFMoniterIDEditClass = new javax.swing.JTextField();
        JTFDepartmentIDEditClass = new javax.swing.JTextField();
        JBTEditEditClass = new javax.swing.JButton();
        JBTCancelEditStudent = new javax.swing.JButton();
        JLBClassID = new javax.swing.JLabel();
        JLBClassName = new javax.swing.JLabel();
        JLBYear = new javax.swing.JLabel();
        JLBMobile = new javax.swing.JLabel();
        JLBEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Class");
        setBackground(new java.awt.Color(31, 34, 43));

        JCBYearEditClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        JBTEditEditClass.setText("Edit");
        JBTEditEditClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTEditEditClassActionPerformed(evt);
            }
        });

        JBTCancelEditStudent.setText("Cancel");
        JBTCancelEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTCancelEditStudentActionPerformed(evt);
            }
        });

        JLBClassID.setForeground(new java.awt.Color(255, 255, 255));
        JLBClassID.setText("Class ID");

        JLBClassName.setForeground(new java.awt.Color(255, 255, 255));
        JLBClassName.setText("Class Name");

        JLBYear.setForeground(new java.awt.Color(255, 255, 255));
        JLBYear.setText("Year");

        JLBMobile.setForeground(new java.awt.Color(255, 255, 255));
        JLBMobile.setText("Mibile");

        JLBEmail.setForeground(new java.awt.Color(255, 255, 255));
        JLBEmail.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLBClassID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBClassName, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(JLBYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFMoniterIDEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBYearEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JTFClassnameEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTFClassIDEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(JBTEditEditClass)
                            .addGap(18, 18, 18)
                            .addComponent(JBTCancelEditStudent))
                        .addComponent(JTFDepartmentIDEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFClassIDEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBClassID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFClassnameEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBClassName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBYearEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBYear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFMoniterIDEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBMobile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFDepartmentIDEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTEditEditClass)
                    .addComponent(JBTCancelEditStudent))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setBounds(470, 200, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void JBTEditEditClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTEditEditClassActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JBTEditEditClassActionPerformed

    private void JBTCancelEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTCancelEditStudentActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_JBTCancelEditStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditClass dialog = new EditClass(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTCancelEditStudent;
    private javax.swing.JButton JBTEditEditClass;
    public javax.swing.JComboBox JCBYearEditClass;
    private javax.swing.JLabel JLBClassID;
    private javax.swing.JLabel JLBClassName;
    private javax.swing.JLabel JLBEmail;
    private javax.swing.JLabel JLBMobile;
    private javax.swing.JLabel JLBYear;
    public javax.swing.JTextField JTFClassIDEditClass;
    public javax.swing.JTextField JTFClassnameEditClass;
    public javax.swing.JTextField JTFDepartmentIDEditClass;
    public javax.swing.JTextField JTFMoniterIDEditClass;
    // End of variables declaration//GEN-END:variables
}
